### ISSUE TITLE
Is download.sh missing ?

### ISSUE THREAD

**Issue by amnano** [progremir/navalmanac#1]

**Comment by progremir** [comment]
Hey @amnano ! Yes, I removed some of the unused stuff from the repo.
It used to recursively download langchain's documentation. If you want you can find it in this repo: https://github.com/sullivan-sean/chat-langchainjs. I cloned it to bootstrap mine. Hope this helps

**Comment by progremir** [comment]
I also updated README file, so I guess this case is closed :)
LMK if I can help you with anything else
